# Generated by Django 3.0.5 on 2023-01-11 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=40)),
                ('specialite', models.CharField(max_length=50)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile_pic/DocteurProfilePic/')),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('creation', models.DateField(auto_now=True)),
                ('miseAjour', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('groupe_sanguin', models.CharField(max_length=10, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile_pic/PatientProfilePic/')),
                ('dossier', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_patient', to='monitoring.DossierMedical')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('patients', models.ManyToManyField(related_name='patients_services', to='monitoring.Patient')),
                ('salles', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitoring.Salle')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=40)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile_pic/SecretaireProfilePic/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_secretaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('docteurs', models.ManyToManyField(related_name='docteurs_rendez_vous', to='monitoring.Docteur')),
                ('patients', models.ManyToManyField(related_name='patients_rendez_vous', to='monitoring.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='rendez_vous',
            field=models.ManyToManyField(related_name='patients_rendez_vous', to='monitoring.RendezVous'),
        ),
        migrations.AddField(
            model_name='patient',
            name='secretaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='monitoring.Secretaire'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('docteurs', models.ManyToManyField(related_name='docteurs_ordonnances', to='monitoring.Docteur')),
                ('dossier_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='monitoring.DossierMedical')),
            ],
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('statut', models.BooleanField(default=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='monitoring.Salle')),
            ],
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_patient', to='monitoring.Patient'),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='monitoring.Service'),
        ),
        migrations.AddField(
            model_name='docteur',
            name='ordonnances',
            field=models.ManyToManyField(related_name='docteurs_ordonnances', to='monitoring.Ordonnance'),
        ),
        migrations.AddField(
            model_name='docteur',
            name='patients',
            field=models.ManyToManyField(related_name='docteurs', to='monitoring.Patient'),
        ),
        migrations.AddField(
            model_name='docteur',
            name='rendez_vous',
            field=models.ManyToManyField(related_name='docteurs_rendez_vous', to='monitoring.RendezVous'),
        ),
        migrations.AddField(
            model_name='docteur',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.Service'),
        ),
        migrations.AddField(
            model_name='docteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_docteur', to=settings.AUTH_USER_MODEL),
        ),
    ]
