# Generated by Django 3.0.5 on 2023-01-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='numero',
        ),
        migrations.AlterField(
            model_name='salle',
            name='nom',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
